name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh_key
          chmod 600 ~/.ssh_key

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh_key root@64.227.184.161 "
            export PATH=/root/.nvm/versions/node/v24.11.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin &&
            cd /root/bms_devops &&
            git pull origin production &&
            npm install -g pnpm &&
            pnpm install &&
            pnpm run build &&
            pm2 restart all
          "
